server:
  port: 9966
spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri:  https://gitee.com/robin_p_liu/edu-config.git  #配置git服务地址
          username: robin_p_liu #配置git用户名
          password: liuping521 #配置git密码
          search-paths:
            - edu-config  #仓库名
          default-label: master # 使用的默认分支，默认为 master
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.11.128:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
